services:
  - type: web
    name: mansurbek
    env: python
    pythonVersion: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: FLASK_SECRET
        sync: false
